import CodeBlock from "@/components/code-snippets/code-block";
import CodeSnippetHero from "@/components/code-snippets/code-snippet-hero";
import CodeSnippetInstroduction from "@/components/code-snippets/code-introduction";
import CodeOverview from "@/components/code-snippets/code-overview";
import KeyConcepts from "@/components/code-snippets/key-concepts";
import StepByStepTutorial from "@/components/code-snippets/step-by-step-tutorial";
import Troubleshooting from "@/components/code-snippets/troubleshooting";

const NginxServiceManagementPage = () => {
  return (
    <main>
      <CodeSnippetHero
        title="How to Manage Nginx Service for Frappe and ERPNext"
        description="Learn how to set up, stop, start, and reload the Nginx service for your Frappe or ERPNext application using Bench CLI commands and locate the Nginx configuration file."
        snippetName="Nginx Service Management"
        language="bash"
        category="Frappe Server Management"
        accentColor="blue"
      />
      <CodeSnippetInstroduction 
        paragraphs={[
          "Managing the Nginx web server is a critical task for any Frappe or ERPNext administrator. Nginx acts as a reverse proxy, serving web pages, handling SSL, and routing requests to the Frappe application. The Bench CLI provides convenient commands to simplify this process.",
          "This guide covers the essential commands for setting up and controlling the Nginx service and shows you where to find the configuration file for advanced customizations."
        ]}
      />
      <CodeBlock
        code={`bench setup nginx
sudo service nginx stop
sudo service nginx reload
sudo service nginx start
# Location of the config file:
frappe-bench/conf/nginx.conf`}
        language="bash"
        fileName="Terminal"
        showLineNumbers={false}
      />
      <CodeOverview
        whatItDoes="This set of commands allows a system administrator to initialize the Nginx configuration for a Frappe bench, and then control the Nginx service (stop, reload, start). It also points to the location of the generated Nginx configuration file."
        whenToUse="Use these commands during the initial setup of a Frappe/ERPNext instance, when deploying changes that require a server restart or configuration reload, or when troubleshooting server-related issues like 502 Bad Gateway errors."
        prerequisites={[
          "A working Frappe bench installation",
          "Sudo/root access on the server",
          "Nginx installed on the server (usually handled by `bench setup production`)",
        ]}
      />
      <KeyConcepts
        concepts={[
          {
            title: "Bench CLI",
            description:
              "The Bench Command Line Interface (CLI) is the primary tool for managing Frappe Framework sites. It automates tasks like installation, updates, site creation, and server process management, including Nginx, Supervisor, and Redis.",
            relatedLink: "https://frappeframework.com/docs/user/en/bench/resources/bench-commands-cheatsheet",
          },
          {
            title: "Nginx as a Reverse Proxy",
            description:
              "In a Frappe setup, Nginx doesn't run the Python application directly. It acts as a reverse proxy, receiving HTTP/S requests from users and forwarding them to the Frappe application server (Gunicorn). It also efficiently serves static assets like CSS, JS, and images.",
            relatedLink: "https://frappeframework.com/docs/user/en/production-deployment",
          },
          {
            title: "nginx.conf",
            description:
              "The `frappe-bench/conf/nginx.conf` file is automatically generated by `bench setup nginx`. It contains server blocks and location directives tailored to your Frappe site, including SSL settings, upstream definitions, and static file locations.",
            relatedLink: "https://frappeframework.com/docs/user/en/bench/guides/setting-up-https",
          },
        ]}
      />
      <StepByStepTutorial
        steps={[
          {
            stepNumber: 1,
            title: "Generate or Update Nginx Configuration",
            explanation:
              "This is the first command you should run. It creates or updates the `nginx.conf` file inside your bench's `conf` directory based on the sites you have created. It will also attempt to create a symbolic link in the system's Nginx configuration directory (e.g., `/etc/nginx/sites-enabled/`).",
            code: `bench setup nginx`,
            language: "bash",
          },
          {
            stepNumber: 2,
            title: "Apply Configuration Changes",
            explanation:
              "After modifying the configuration (or after running `bench setup nginx`), you need to tell Nginx to reload its settings without dropping connections. The `reload` command is the graceful way to do this.",
            code: `sudo service nginx reload`,
            language: "bash",
          },
          {
            stepNumber: 3,
            title: "Restarting the Nginx Service",
            explanation:
              "If a simple reload isn't enough or if you need to perform maintenance, you can stop and start the service. This is a 'hard' restart and will briefly drop active connections. This is less common than `reload`.",
            code: `sudo service nginx stop\nsudo service nginx start`,
            language: "bash",
          },
          {
            stepNumber: 4,
            title: "Locate and Inspect the Configuration File",
            explanation:
              "To make advanced changes, such as custom redirects, security headers, or SSL certificate paths, you need to edit the configuration file directly. It's located in the `conf` directory within your bench folder. After editing, remember to run `sudo service nginx reload`.",
            code: `# Navigate to your bench directory first, e.g., cd ~/frappe-bench\ncat conf/nginx.conf`,
            language: "bash",
          },
        ]}
      />
      <Troubleshooting
        items={[
          {
            problem: "502 Bad Gateway Error after running commands.",
            solution:
              "A 502 error often means Nginx is running but cannot connect to the Frappe application server (Gunicorn). Check the status of Supervisor processes with `sudo supervisorctl status`. If `frappe-bench-web` processes are not running, check the logs in `frappe-bench/logs/web.log` for Python errors.",
          },
          {
            problem: "The command `sudo service nginx reload` fails with an error.",
            solution:
              "This usually indicates a syntax error in your Nginx configuration. Run `sudo nginx -t` to test the configuration files. The output will point you to the exact file and line number containing the error.",
          },
          {
            problem: "My changes to `nginx.conf` are not taking effect.",
            solution:
              "Ensure you have reloaded the Nginx service after saving your changes by running `sudo service nginx reload`. Also, verify that the symbolic link in `/etc/nginx/sites-enabled/` correctly points to your `frappe-bench/conf/nginx.conf` file.",
          },
        ]}
      />
    </main>
  );
};

export default NginxServiceManagementPage;
