services:
  nextjs-finbyz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: finbyzwebsite-nextjs:latest 
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    