services:
  nextjs:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      - ../:/app  # optional for local dev
