services:
  nextjs-finbyz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: ghcr.io/finbyz/finbyzwebsite-nextjs 
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    