import Section from '@/components/sections/Section';
import List from '@/components/sections/list';
import { FC } from 'react';

const OutputSection: FC = () => {
  return (
    <Section className="container-custom py-8">
      <h2 className="text-2xl font-bold mb-4">Output</h2>
      <ol>
        <li>A ready-to-publish LinkedIn post</li>
        <li>Branded visuals auto generated by AI agents</li>
        <li>Option to publish now or schedule later inside ERPNext</li>
      </ol>
      <p className="text-lg mt-4">With Content Spark, your marketing is faster, smarter, and always on-brand.</p>
    </Section>
  );
};

export default OutputSection;